In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

train=pd.read_csv(r'C:\Users\HP\Desktop\ML\Human-Activity-Recog\csv_files\train.csv')
test=pd.read_csv(r'C:\Users\HP\Desktop\ML\Human-Activity-Recog\csv_files\test.csv')

In [2]:
X_train=train.drop(['subject','Activity','ActivityName'],axis=1)
Y_train=train['ActivityName']

X_test=test.drop(['subject','Activity','ActivityName'],axis=1)
Y_test=test['ActivityName']

In [3]:
from datetime import datetime

def run_model(model,model_name):
    result=dict()
    result['model_name']=model_name
    #training
    print("Training........")
    t1=datetime.now()
    model.fit(X_train,Y_train)
    t2=datetime.now()
    result['training_time']=t2-t1
    print("Training Complete!  time taken="+str(t2-t1))
    
    #testing
    print("Testing.......")
    t1=datetime.now()
    pred=model.predict(X_test)
    t2=datetime.now()
    result['testing_time']=t2-t1
    print("Testing Done!  time taken="+str(t2-t1))
    
    #Checking model performance
    accuracy=metrics.accuracy_score(Y_test,pred)
    result['accuracy']=accuracy
    confusion_matrix=metrics.confusion_matrix(Y_test,pred)
    result['confusion_matrix']=confusion_matrix
    classification_report=metrics.classification_report(Y_test,pred)
    result['classification_report']=classification_report
    
    print("accuracy: ",accuracy)
    print("\n\nconfusion_matrix:\n",confusion_matrix)
    print("\n\n",classification_report)
    
    result['model']=model
    
    return result

<h1>Using Logistic Regression</h1>

In [4]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
from sklearn.model_selection import GridSearchCV

params={'C':[0.01,0.1,1,10,50,100],'penalty':['l1','l2']}
lrgrid=GridSearchCV(LogisticRegression(),param_grid=params,cv=3,n_jobs=-1)
lrresult=run_model(lrgrid,'Logistic Regression')


Training........


C:\Users\HP\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\HP\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


Training Complete!  time taken=0:02:34.000630
Testing.......
Testing Done!  time taken=0:00:00.156216
accuracy:  0.9619952494061758


confusion_matrix:
 [[537   0   0   0   0   0]
 [  2 426  59   0   0   4]
 [  0  12 519   1   0   0]
 [  0   0   0 495   1   0]
 [  0   0   0   3 410   7]
 [  0   0   0  23   0 448]]


                     precision    recall  f1-score   support

            LAYING       1.00      1.00      1.00       537
           SITTING       0.97      0.87      0.92       491
          STANDING       0.90      0.98      0.94       532
           WALKING       0.95      1.00      0.97       496
WALKING_DOWNSTAIRS       1.00      0.98      0.99       420
  WALKING_UPSTAIRS       0.98      0.95      0.96       471

         micro avg       0.96      0.96      0.96      2947
         macro avg       0.96      0.96      0.96      2947
      weighted avg       0.96      0.96      0.96      2947



In [5]:
lrmodel=lrresult['model']
print("\nbest params:\n",lrmodel.best_params_)
print("\nbest score:\n",lrmodel.best_score_)


best params:
 {'C': 50, 'penalty': 'l2'}

best score:
 0.9450489662676823


<h1>Using KNN</h1>

In [6]:
from sklearn.neighbors import KNeighborsClassifier
params={'n_neighbors':[3,5,7,9]}
knngrid=GridSearchCV(KNeighborsClassifier(),param_grid=params,cv=3,n_jobs=-1)
knnresult=run_model(knngrid,'KNN')

Training........
Training Complete!  time taken=0:03:24.616886
Testing.......
Testing Done!  time taken=0:00:30.226181
accuracy:  0.9053274516457415


confusion_matrix:
 [[534   2   1   0   0   0]
 [  0 394  93   0   0   4]
 [  0  37 495   0   0   0]
 [  0   0   0 485  10   1]
 [  0   0   0  47 333  40]
 [  0   0   0  38   6 427]]


                     precision    recall  f1-score   support

            LAYING       1.00      0.99      1.00       537
           SITTING       0.91      0.80      0.85       491
          STANDING       0.84      0.93      0.88       532
           WALKING       0.85      0.98      0.91       496
WALKING_DOWNSTAIRS       0.95      0.79      0.87       420
  WALKING_UPSTAIRS       0.90      0.91      0.91       471

         micro avg       0.91      0.91      0.91      2947
         macro avg       0.91      0.90      0.90      2947
      weighted avg       0.91      0.91      0.90      2947



In [7]:
knnmodel=knnresult['model']
print("\nbest params:\n",knnmodel.best_params_)
print("\nbest score:\n",knnmodel.best_score_)


best params:
 {'n_neighbors': 9}

best score:
 0.8930903155603918


<h1>Using Gaussian NB</h1>

In [8]:
from sklearn.naive_bayes import GaussianNB
params={'var_smoothing':[1e-11,1e-9,1e-7,1e-5]}
nbgrid=GridSearchCV(GaussianNB(),param_grid=params,cv=3,n_jobs=-1)
nbresult=run_model(nbgrid,'Gaussian NB')

Training........
Training Complete!  time taken=0:00:05.724484
Testing.......
Testing Done!  time taken=0:00:00.429856
accuracy:  0.8004750593824228


confusion_matrix:
 [[474  60   0   0   0   3]
 [  5 260 219   0   0   7]
 [  6  11 501   0   0  14]
 [  0   0   0 416  42  38]
 [  0   0   0  80 257  83]
 [  0   0   0   9  11 451]]


                     precision    recall  f1-score   support

            LAYING       0.98      0.88      0.93       537
           SITTING       0.79      0.53      0.63       491
          STANDING       0.70      0.94      0.80       532
           WALKING       0.82      0.84      0.83       496
WALKING_DOWNSTAIRS       0.83      0.61      0.70       420
  WALKING_UPSTAIRS       0.76      0.96      0.85       471

         micro avg       0.80      0.80      0.80      2947
         macro avg       0.81      0.79      0.79      2947
      weighted avg       0.81      0.80      0.79      2947



In [18]:
nbmodel=nbresult['model']
print("\nbest params:\n",nbmodel.best_params_)
print("\nbest score:\n",nbmodel.best_score_)


best params:
 {'var_smoothing': 1e-05}

best score:
 0.7616974972796517


<h1>Using Linear SVM</h1>

In [19]:
from sklearn.svm import LinearSVC
params={'C':[0.01,0.1,1,10,100]}
lsvmgrid=GridSearchCV(LinearSVC(),param_grid=params,cv=3,n_jobs=-1)
lsvmresult=run_model(lsvmgrid,'Linear SVM')

Training........
Training Complete!  time taken=0:00:39.214242
Testing.......
Testing Done!  time taken=0:00:00.015622
accuracy:  0.9684424838819138


confusion_matrix:
 [[537   0   0   0   0   0]
 [  2 444  42   0   0   3]
 [  0  22 510   0   0   0]
 [  0   0   0 496   0   0]
 [  0   0   0   2 413   5]
 [  0   0   0  17   0 454]]


                     precision    recall  f1-score   support

            LAYING       1.00      1.00      1.00       537
           SITTING       0.95      0.90      0.93       491
          STANDING       0.92      0.96      0.94       532
           WALKING       0.96      1.00      0.98       496
WALKING_DOWNSTAIRS       1.00      0.98      0.99       420
  WALKING_UPSTAIRS       0.98      0.96      0.97       471

         micro avg       0.97      0.97      0.97      2947
         macro avg       0.97      0.97      0.97      2947
      weighted avg       0.97      0.97      0.97      2947



C:\Users\HP\Anaconda3\lib\site-packages\sklearn\svm\base.py:931: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


In [20]:
lsvmmodel=lsvmresult['model']
print("\nbest params:\n",lsvmmodel.best_params_)
print("\nbest score:\n",lsvmmodel.best_score_)


best params:
 {'C': 1}

best score:
 0.9454570184983678


<h1>Using kernel SVM</h1>

In [21]:
from sklearn.svm import SVC
params={'C':[0.01,0.1,1,10,100]}
ksvmgrid=GridSearchCV(SVC(kernel='rbf'),param_grid=params,cv=3,n_jobs=-1)
ksvmresult=run_model(ksvmgrid,'Kernel SVM')

Training........


C:\Users\HP\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


Training Complete!  time taken=0:02:49.244386
Testing.......
Testing Done!  time taken=0:00:02.977306
accuracy:  0.9647098744485918


confusion_matrix:
 [[537   0   0   0   0   0]
 [  0 437  52   0   0   2]
 [  0  14 518   0   0   0]
 [  0   0   0 493   3   0]
 [  0   0   0   4 404  12]
 [  0   0   0  17   0 454]]


                     precision    recall  f1-score   support

            LAYING       1.00      1.00      1.00       537
           SITTING       0.97      0.89      0.93       491
          STANDING       0.91      0.97      0.94       532
           WALKING       0.96      0.99      0.98       496
WALKING_DOWNSTAIRS       0.99      0.96      0.98       420
  WALKING_UPSTAIRS       0.97      0.96      0.97       471

         micro avg       0.96      0.96      0.96      2947
         macro avg       0.97      0.96      0.96      2947
      weighted avg       0.97      0.96      0.96      2947



In [22]:
ksvmmodel=ksvmresult['model']
print("\nbest params:\n",ksvmmodel.best_params_)
print("\nbest score:\n",ksvmmodel.best_score_)


best params:
 {'C': 100}

best score:
 0.9458650707290533


<h1>Using Decision Tree</h1>

In [23]:
from sklearn.tree import DecisionTreeClassifier
params={'max_depth':[10,15,20,25,30,50]}
dtgrid=GridSearchCV(DecisionTreeClassifier(criterion='gini',max_features='sqrt'),param_grid=params,cv=3,n_jobs=-1)
dtresult=run_model(dtgrid,'Decision Tree')

Training........
Training Complete!  time taken=0:00:02.466103
Testing.......
Testing Done!  time taken=0:00:00
accuracy:  0.8167628096369189


confusion_matrix:
 [[479  45  13   0   0   0]
 [ 14 395  82   0   0   0]
 [ 20  71 440   0   0   1]
 [  0   0   0 420  38  38]
 [  0   0   0  41 310  69]
 [  4   1   0  63  40 363]]


                     precision    recall  f1-score   support

            LAYING       0.93      0.89      0.91       537
           SITTING       0.77      0.80      0.79       491
          STANDING       0.82      0.83      0.82       532
           WALKING       0.80      0.85      0.82       496
WALKING_DOWNSTAIRS       0.80      0.74      0.77       420
  WALKING_UPSTAIRS       0.77      0.77      0.77       471

         micro avg       0.82      0.82      0.82      2947
         macro avg       0.82      0.81      0.81      2947
      weighted avg       0.82      0.82      0.82      2947



In [24]:
dtmmodel=dtresult['model']
print("\nbest params:\n",dtmmodel.best_params_)
print("\nbest score:\n",dtmmodel.best_score_)


best params:
 {'max_depth': 50}

best score:
 0.823993471164309


<h1>Using Random Forest</h1>

In [25]:
from sklearn.ensemble import RandomForestClassifier

rfmodel=RandomForestClassifier(n_estimators=1000,n_jobs=-1)
rfresult=run_model(rfmodel,'Random Forest')
rfmodel=rfresult['model']

Training........
Training Complete!  time taken=0:00:46.293426
Testing.......
Testing Done!  time taken=0:00:00.692680
accuracy:  0.9243298269426535


confusion_matrix:
 [[537   0   0   0   0   0]
 [  0 435  56   0   0   0]
 [  0  44 488   0   0   0]
 [  0   0   0 481   7   8]
 [  0   0   0  19 355  46]
 [  0   0   0  36   7 428]]


                     precision    recall  f1-score   support

            LAYING       1.00      1.00      1.00       537
           SITTING       0.91      0.89      0.90       491
          STANDING       0.90      0.92      0.91       532
           WALKING       0.90      0.97      0.93       496
WALKING_DOWNSTAIRS       0.96      0.85      0.90       420
  WALKING_UPSTAIRS       0.89      0.91      0.90       471

         micro avg       0.92      0.92      0.92      2947
         macro avg       0.93      0.92      0.92      2947
      weighted avg       0.93      0.92      0.92      2947



<h1>Using Gradient Boosting</h1>

In [26]:
from sklearn.ensemble import GradientBoostingClassifier
params={'learning_rate':[0.1],'n_estimators':[100]}
gbgrid=GridSearchCV(GradientBoostingClassifier(),param_grid=params,cv=3,n_jobs=-1)
gbresult=run_model(gbgrid,'Gradient Boosting')

Training........
Training Complete!  time taken=0:06:43.979135
Testing.......
Testing Done!  time taken=0:00:00.120568
accuracy:  0.9392602646759416


confusion_matrix:
 [[537   0   0   0   0   0]
 [  0 418  70   0   0   3]
 [  0  33 499   0   0   0]
 [  0   0   0 486   4   6]
 [  0   0   0   7 387  26]
 [  0   1   0  24   5 441]]


                     precision    recall  f1-score   support

            LAYING       1.00      1.00      1.00       537
           SITTING       0.92      0.85      0.89       491
          STANDING       0.88      0.94      0.91       532
           WALKING       0.94      0.98      0.96       496
WALKING_DOWNSTAIRS       0.98      0.92      0.95       420
  WALKING_UPSTAIRS       0.93      0.94      0.93       471

         micro avg       0.94      0.94      0.94      2947
         macro avg       0.94      0.94      0.94      2947
      weighted avg       0.94      0.94      0.94      2947



In [27]:
gbmmodel=gbresult['model']
print("\nbest params:\n",gbmmodel.best_params_)
print("\nbest score:\n",gbmmodel.best_score_)


best params:
 {'learning_rate': 0.1, 'n_estimators': 100}

best score:
 0.9091403699673558


<br><br><br>
<h1>Comparing all models</h1>

In [49]:


results=[lrresult,knnresult,nbresult,lsvmresult,ksvmresult,dtresult,rfresult,gbresult]
for r in results:
    print(str(r['model_name'])+"\nTraining Time:"+str(r['training_time'])+"\tAccuracy:"+str(r['accuracy']*100)+"\n")




Logistic Regression
Training Time:0:02:34.000630	Accuracy:96.19952494061758

KNN
Training Time:0:03:24.616886	Accuracy:90.53274516457415

Gaussian NB
Training Time:0:00:05.724484	Accuracy:80.04750593824228

Linear SVM
Training Time:0:00:39.214242	Accuracy:96.84424838819137

Kernel SVM
Training Time:0:02:49.244386	Accuracy:96.47098744485918

Decision Tree
Training Time:0:00:02.466103	Accuracy:81.6762809636919

Random Forest
Training Time:0:00:46.293426	Accuracy:92.43298269426535

Gradient Boosting
Training Time:0:06:43.979135	Accuracy:93.92602646759416

